In [ ]:
import numpy as np
from scipy.linalg import svd

def generateTestMatrix(matrixSize):
    """
    Генерирует верхнюю треугольную тестовую матрицу
    с 1 на главной диагонали и -1 над диагональю
    """
    testMatrix = np.full((matrixSize, matrixSize), -1.0)
    np.fill_diagonal(testMatrix, 1)
    testMatrix = np.triu(testMatrix)
    return testMatrix

def generateExactSolution(matrixSize, solutionType):
    """
    Генерирует точное решение системы
    """
    if solutionType == 1:
        # Единичный вектор
        exactSolution = np.ones(matrixSize)
    elif solutionType == 2:
        # Вектор с возрастающими компонентами
        exactSolution = np.ones(matrixSize)
        for i in range(matrixSize):
            exactSolution[i] += np.sqrt(i)
    
    return exactSolution

def generateRightHandSide(matrix, solution):
    """
    Вычисляет правую часть системы уравнений
    """
    return matrix @ solution

def solveWithDirectMethod(matrix, rightHandSide, exactSolution):
    """
    Решает систему прямым методом и вычисляет ошибку
    """
    computedSolution = np.linalg.solve(matrix, rightHandSide)
    solutionError = np.linalg.norm(computedSolution - exactSolution)
    return computedSolution, solutionError

def solveWithTruncatedSVD(matrix, rightHandSide, exactSolution):
    """
    Решает систему методом усеченного SVD
    """
    # SVD разложение
    leftSingularVectors, singularValues, rightSingularVectorsTransposed = svd(matrix)
    
    # Усекаем наименьшее сингулярное значение
    truncatedSigma = np.diag(singularValues[:-1])
    invertedSigma = np.diag(1.0 / singularValues[:-1])
    
    # основные и дополнительные компоненты
    mainLeftVectors = leftSingularVectors.T[:-1].T
    additionalLeftVectors = leftSingularVectors.T[-1:].T
    
    mainRightVectors = rightSingularVectorsTransposed[:-1].T
    additionalRightVectors = rightSingularVectorsTransposed[-1:].T
    
    #  основное решение
    mainSolution = mainRightVectors @ invertedSigma @ mainLeftVectors.T @ rightHandSide
    
    # Корректируем решение с использованием дополнительной компоненты
    correctionCoefficient = (exactSolution[0] - mainSolution[0]) / additionalRightVectors[0]
    finalSolution = mainSolution + correctionCoefficient * additionalRightVectors.T
    
    return finalSolution

def main():
    matrixSize = 50
    solutionType = 2
    
    testMatrix = generateTestMatrix(matrixSize)
    exactSolution = generateExactSolution(matrixSize, solutionType)
    rightHandSide = generateRightHandSide(testMatrix, exactSolution)
    
    # Решение прямым методом
    directSolution, directError = solveWithDirectMethod(testMatrix, rightHandSide, exactSolution)
    print(f"Прямой метод: n = {matrixSize}, ошибка = {directError:.5e}")
    
    # Решение методом усеченного SVD
    svdSolution = solveWithTruncatedSVD(testMatrix, rightHandSide, exactSolution)
    svdError = np.linalg.norm(svdSolution - exactSolution)
    print(f"Метод SVD: n = {matrixSize}, ошибка = {svdError:.5e}")
    
    print("\nСравнение решений:")
    print("Точное решение (первые 5 элементов):", exactSolution[:5])
    print("Прямой метод (первые 5 элементов):", directSolution[:5])
    print("Метод SVD (первые 5 элементов):", svdSolution[:5])

if __name__ == "__main__":
    main()

Прямой метод: n = 50, ошибка = 5.92757e-02
Метод SVD: n = 50, ошибка = 5.89519e-13

Сравнение решений:
Точное решение (первые 5 элементов): [1.         2.         2.41421356 2.73205081 3.        ]
Прямой метод (первые 5 элементов): [1.05133424 2.02566712 2.42704712 2.73846759 3.00320839]
Метод SVD (первые 5 элементов): [[1.         2.         2.41421356 2.73205081 3.         3.23606798
  3.44948974 3.64575131 3.82842712 4.         4.16227766 4.31662479
  4.46410162 4.60555128 4.74165739 4.87298335 5.         5.12310563
  5.24264069 5.35889894 5.47213595 5.58257569 5.69041576 5.79583152
  5.89897949 6.         6.09901951 6.19615242 6.29150262 6.38516481
  6.47722558 6.56776436 6.65685425 6.74456265 6.83095189 6.91607978
  7.         7.08276253 7.164414   7.244998   7.32455532 7.40312424
  7.4807407  7.55743852 7.63324958 7.70820393 7.78232998 7.8556546
  7.92820323 8.        ]]


In [3]:
import numpy as np
from scipy.linalg import svd

def generateTestMatrix(matrixSize):
    """
    Генерирует верхнюю треугольную тестовую матрицу
    с 1 на главной диагонали и -1 над диагональю
    """
    testMatrix = np.full((matrixSize, matrixSize), -1.0)
    np.fill_diagonal(testMatrix, 1)
    testMatrix = np.triu(testMatrix)
    return testMatrix

def generateExactSolution(matrixSize, solutionType):
    """
    Генерирует точное решение системы
    """
    if solutionType == 1:
        # Единичный вектор
        exactSolution = np.ones(matrixSize)
    elif solutionType == 2:
        # Вектор с возрастающими компонентами
        exactSolution = np.ones(matrixSize)
        for i in range(matrixSize):
            exactSolution[i] += np.sqrt(i)
    
    return exactSolution

def generateRightHandSide(matrix, solution):
    """
    Вычисляет правую часть системы уравнений
    """
    return matrix @ solution

def solveWithDirectMethod(matrix, rightHandSide, exactSolution):
    """
    Решает систему прямым методом и вычисляет ошибку
    """
    computedSolution = np.linalg.solve(matrix, rightHandSide)
    solutionError = np.linalg.norm(computedSolution - exactSolution)
    return computedSolution, solutionError

def computeSingularValues(matrix):
    """
    Вычисляет и возвращает сингулярные числа матрицы
    """
    _, singularValues, _ = svd(matrix)
    return singularValues

def solveWithTruncatedSVD(matrix, rightHandSide, exactSolution):
    """
    Решает систему методом усеченного SVD
    """
    # SVD разложение
    leftSingularVectors, singularValues, rightSingularVectorsTransposed = svd(matrix)
    
    # Усекаем наименьшее сингулярное значение
    truncatedSigma = np.diag(singularValues[:-1])
    invertedSigma = np.diag(1.0 / singularValues[:-1])
    
    # Разделяем матрицы на основные и дополнительные компоненты
    mainLeftVectors = leftSingularVectors.T[:-1].T
    additionalLeftVectors = leftSingularVectors.T[-1:].T
    
    mainRightVectors = rightSingularVectorsTransposed[:-1].T
    additionalRightVectors = rightSingularVectorsTransposed[-1:].T
    
    # Вычисляем основное решение
    mainSolution = mainRightVectors @ invertedSigma @ mainLeftVectors.T @ rightHandSide
    
    # Корректируем решение с использованием дополнительной компоненты
    correctionCoefficient = (exactSolution[0] - mainSolution[0]) / additionalRightVectors[0]
    finalSolution = mainSolution + correctionCoefficient * additionalRightVectors.T
    
    return finalSolution, singularValues

def main():
    matrixSize = 50
    solutionType = 2
    
    # Генерация данных
    testMatrix = generateTestMatrix(matrixSize)
    exactSolution = generateExactSolution(matrixSize, solutionType)
    rightHandSide = generateRightHandSide(testMatrix, exactSolution)
    
    # Вычисляем и выводим сингулярные числа
    singularValues = computeSingularValues(testMatrix)
    print("Сингулярные числа матрицы:")
    print("-" * 50)
    
    # Выводим все сингулярные числа
    for i, value in enumerate(singularValues):
        print(f"σ{i+1} = {value:.10e}")
    
    # Дополнительная информация о сингулярных числах
    print("\nХарактеристики сингулярных чисел:")
    print(f"Максимальное: {np.max(singularValues):.10e}")
    print(f"Минимальное:  {np.min(singularValues):.10e}")
    print(f"Число обусловленности: {np.max(singularValues)/np.min(singularValues):.10e}")
    print(f"Сумма: {np.sum(singularValues):.10e}")
    
    # убывания сингулярных чисел
    print("\nПервые 10 сингулярных чисел:")
    for i in range(min(10, len(singularValues))):
        print(f"σ{i+1}: {singularValues[i]:.10e}")
    
    print("\nПоследние 5 сингулярных чисел:")
    for i in range(max(0, len(singularValues)-5), len(singularValues)):
        print(f"σ{i+1}: {singularValues[i]:.10e}")
    
    # Решение прямым методом
    directSolution, directError = solveWithDirectMethod(testMatrix, rightHandSide, exactSolution)
    print(f"\nПрямой метод: n = {matrixSize}, ошибка = {directError:.5e}")
    
    # Решение методом усеченного SVD
    svdSolution, svdSingularValues = solveWithTruncatedSVD(testMatrix, rightHandSide, exactSolution)
    svdError = np.linalg.norm(svdSolution - exactSolution)
    print(f"Метод SVD: n = {matrixSize}, ошибка = {svdError:.5e}")
    
    # Показываем какое сингулярное число было отброшено
    smallestSingularValue = svdSingularValues[-1]
    print(f"Наименьшее сингулярное число (отброшенное): {smallestSingularValue:.10e}")
    
    print("\nСравнение решений:")
    print("Точное решение (первые 5 элементов):", exactSolution[:5])
    print("Прямой метод (первые 5 элементов):", directSolution[:5])
    print("Метод SVD (первые 5 элементов):", svdSolution[:5])

def analyzeMatrixProperties():
    """
    Дополнительная функция для анализа свойств матрицы разных размеров
    """
    print("\n" + "="*60)
    print("Анализ сингулярных чисел для матриц разных размеров")
    print("="*60)
    
    sizes = [10, 20, 50, 100]
    
    for size in sizes:
        matrix = generateTestMatrix(size)
        singularValues = computeSingularValues(matrix)
        
        print(f"\nРазмер матрицы: {size}x{size}")
        # print(f"Число обусловленности: {np.max(singularValues)/np.min(singularValues):.2e}")
        print(f"Количество сингулярных чисел < 1e-10: {np.sum(singularValues < 1e-10)}")
        print(f"Минимальное сингулярное число: {np.min(singularValues):.2e}")

if __name__ == "__main__":
    main()
    analyzeMatrixProperties()

Сингулярные числа матрицы:
--------------------------------------------------
σ1 = 3.0910443808e+01
σ2 = 1.0394699940e+01
σ3 = 6.3448080503e+00
σ4 = 4.6452130160e+00
σ5 = 3.7269924612e+00
σ6 = 3.1620012447e+00
σ7 = 2.7854878726e+00
σ8 = 2.5205927970e+00
σ9 = 2.3267035962e+00
σ10 = 2.1804061244e+00
σ11 = 2.0673054856e+00
σ12 = 1.9781049028e+00
σ13 = 1.9065615558e+00
σ14 = 1.8483485092e+00
σ15 = 1.8003867589e+00
σ16 = 1.7604358937e+00
σ17 = 1.7268340669e+00
σ18 = 1.6983277222e+00
σ19 = 1.6739571576e+00
σ20 = 1.6529778603e+00
σ21 = 1.6348053512e+00
σ22 = 1.6189758254e+00
σ23 = 1.6051176236e+00
σ24 = 1.5929302556e+00
σ25 = 1.5821687797e+00
σ26 = 1.5726320315e+00
σ27 = 1.5641536577e+00
σ28 = 1.5565952196e+00
σ29 = 1.5498408375e+00
σ30 = 1.5437929983e+00
σ31 = 1.5383692469e+00
σ32 = 1.5334995551e+00
σ33 = 1.5291242167e+00
σ34 = 1.5251921520e+00
σ35 = 1.5216595340e+00
σ36 = 1.5184886697e+00
σ37 = 1.5156470856e+00
σ38 = 1.5131067752e+00
σ39 = 1.5108435798e+00
σ40 = 1.5088366755e+00
σ41 = 1.507

In [26]:
import numpy as np

def analyze_svd(A):
    print("=" * 60)
    print(f"АНАЛИЗ SVD ДЛЯ МАТРИЦЫ РАЗМЕРОМ {A.shape}")
    print("=" * 60)
    
    U, s, Vt = np.linalg.svd(A, full_matrices=True)
    
    print("\n1. МАТРИЦА A:")
    print(A)
    print(f"Размер A: {A.shape}")
    
    print(f"\n2. СИНГУЛЯРНЫЕ ЧИСЛА s:")
    print(s)
    print(f"Размер s: {s.shape}")
    print(f"Сумма сингулярных чисел: {np.sum(s)}")
    
    print(f"\n3. МАТРИЦА U:")
    print(U)
    print(f"Размер U: {U.shape}")
    
    print(f"U ортогональна? (U^T @ U = I): {np.allclose(U.T @ U, np.eye(U.shape[0]))}")
    print(f"U унитарна? (U @ U^T = I): {np.allclose(U @ U.T, np.eye(U.shape[0]))}")
    
    print(f"\n4. МАТРИЦА Vt (V транспонированная):")
    print(Vt)
    print(f"Размер Vt: {Vt.shape}")
    
    V = Vt.T
    print(f"V ортогональна? (V^T @ V = I): {np.allclose(V.T @ V, np.eye(V.shape[1]))}")
    print(f"V унитарна? (V @ V^T = I): {np.allclose(V @ V.T, np.eye(V.shape[0]))}")
    
    print(f"\n5. ПРОВЕРКА РАЗЛОЖЕНИЯ A = U @ Σ @ Vt:")
    
    # Создаем полную матрицу Σ
    Sigma = np.zeros_like(A, dtype=float)
    min_dim = min(A.shape)
    Sigma[:min_dim, :min_dim] = np.diag(s)
    
    A_reconstructed = U @ Sigma @ Vt
    print(f"Ошибка восстановления: {np.linalg.norm(A - A_reconstructed)}")
    print(f"Восстановление точное? {np.allclose(A, A_reconstructed)}")
    
    print(f"\n6. СТРУКТУРА МАТРИЦ:")
    print(f"U: {U.shape} - левые сингулярные векторы")
    print(f"s: {s.shape} - сингулярные числа") 
    print(f"Vt: {Vt.shape} - правые сингулярные векторы (транспонированные)")
    print(f"Σ (полная): {Sigma.shape} - диагональная матрица сингулярных чисел")
    
    return U, s, Vt

print("ТЕСТ НА МАТРИЦЕ 3x3")
A_small = np.array([[1, -1, -1],
                   [0,  1, -1], 
                   [0,  0,  1]])
U1, s1, Vt1 = analyze_svd(A_small)

print("\n" + "="*60)
print("ТЕСТ НА МАТРИЦЕ ИЗ ЗАДАЧИ (n=4)")
print("="*60)

def create_matrix_A(n):
    A = np.zeros((n, n))
    for i in range(n):
        A[i, i] = 1
        for j in range(i+1, n):
            A[i, j] = -1
    return A

A4 = create_matrix_A(4)
U2, s2, Vt2 = analyze_svd(A4)

print("\n" + "="*60)
print("ПОДРОБНЫЙ АНАЛИЗ ДЛЯ n=4")
print("="*60)

print("Левые сингулярные векторы (столбцы U):")
for i in range(U2.shape[1]):
    print(f"u{i+1}: {U2[:, i]}")

print("\nПравые сингулярные векторы (строки Vt):")
for i in range(Vt2.shape[0]):
    print(f"v{i+1}: {Vt2[i, :]}")

print(f"\nСингулярные числа: {s2}")

print("\nВОССТАНОВЛЕНИЕ ПО КОМПОНЕНТАМ:")
A_recon = np.zeros_like(A4)
for i in range(len(s2)):
    component = s2[i] * np.outer(U2[:, i], Vt2[i, :])
    A_recon += component
    print(f"Компонент {i+1} (σ{i+1}={s2[i]:.4f}):")
    print(component)
    print(f"Сумма до компонента {i+1}:")
    print(A_recon)
    print()

print("Исходная матрица A:")
print(A4)
print("Восстановленная матрица A:")
print(A_recon)

ТЕСТ НА МАТРИЦЕ 3x3
АНАЛИЗ SVD ДЛЯ МАТРИЦЫ РАЗМЕРОМ (3, 3)

1. МАТРИЦА A:
[[ 1 -1 -1]
 [ 0  1 -1]
 [ 0  0  1]]
Размер A: (3, 3)

2. СИНГУЛЯРНЫЕ ЧИСЛА s:
[1.879385 1.532089 0.347296]
Размер s: (3,)
Сумма сингулярных чисел: 3.7587704831436333

3. МАТРИЦА U:
[[ 0.84403   0.449099  0.293128]
 [ 0.293128 -0.84403   0.449099]
 [-0.449099  0.293128  0.84403 ]]
Размер U: (3, 3)
U ортогональна? (U^T @ U = I): True
U унитарна? (U @ U^T = I): True

4. МАТРИЦА Vt (V транспонированная):
[[ 0.449099 -0.293128 -0.84403 ]
 [ 0.293128 -0.84403   0.449099]
 [ 0.84403   0.449099  0.293128]]
Размер Vt: (3, 3)
V ортогональна? (V^T @ V = I): True
V унитарна? (V @ V^T = I): True

5. ПРОВЕРКА РАЗЛОЖЕНИЯ A = U @ Σ @ Vt:
Ошибка восстановления: 5.351097117767103e-16
Восстановление точное? True

6. СТРУКТУРА МАТРИЦ:
U: (3, 3) - левые сингулярные векторы
s: (3,) - сингулярные числа
Vt: (3, 3) - правые сингулярные векторы (транспонированные)
Σ (полная): (3, 3) - диагональная матрица сингулярных чисел

ТЕСТ НА МАТРИ

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def create_matrix_A(n):
    A = np.zeros((n, n))
    for i in range(n):
        A[i, i] = 1
        for j in range(i+1, n):
            A[i, j] = -1
    return A

def solve_with_svd(A, b, truncate=True):
    U, s, Vt = np.linalg.svd(A, full_matrices=True)
    
    if truncate:
        # Усекаем: заменяем наименьшее сингулярное число на 0
        s_trunc = s.copy()
        s_trunc[-1] = 0
        # матрица с усечением
        A_pinv = Vt.T @ np.diag(np.where(s_trunc != 0, 1/s_trunc, 0)) @ U.T
    else:
        A_pinv = np.linalg.pinv(A)
    return A_pinv @ b

n_small = 10
n_large = 100

A_small = create_matrix_A(n_small)
A_large = create_matrix_A(n_large)

print("Матрица A для n=10:")
print(A_small)
print(f"\nОпределитель A для n=10: {np.linalg.det(A_small)}")

x_first_true = np.ones(n_small)
b_first = A_small @ x_first_true

x_first_recovered = np.linalg.solve(A_small, b_first)

print(f"\nПервый случай (единичный вектор):")
print(f"Исходный x: {x_first_true}")
print(f"Восстановленный x: {x_first_recovered}")
print(f"Ошибка: {np.linalg.norm(x_first_true - x_first_recovered)}")

# Второй случай: x_i = 1 + sqrt(i-1)
def create_perturbed_vector(n):
    return np.array([1 + np.sqrt(i) for i in range(n)])

x_second_true_small = create_perturbed_vector(n_small)
x_second_true_large = create_perturbed_vector(n_large)

b_second_small = A_small @ x_second_true_small
b_second_large = A_large @ x_second_true_large

# Восстанавливаем решения обычным методом
x_second_recovered_small = np.linalg.solve(A_small, b_second_small)
x_second_recovered_large = np.linalg.solve(A_large, b_second_large)

print(f"\nВторой случай для n=10:")
print(f"Исходный x: {x_second_true_small}")
print(f"Восстановленный x: {x_second_recovered_small}")
print(f"Ошибка: {np.linalg.norm(x_second_true_small - x_second_recovered_small)}")

print(f"\nВторой случай для n=100:")
print(f"Ошибка: {np.linalg.norm(x_second_true_large - x_second_recovered_large)}")

# Решаем с помощью SVD с усечением
x_svd_small = solve_with_svd(A_small, b_second_small, truncate=True)
x_svd_large = solve_with_svd(A_large, b_second_large, truncate=True)

print(f"\nSVD решение с усечением для n=10:")
print(f"Ошибка: {np.linalg.norm(x_second_true_small - x_svd_small)}")

print(f"\nSVD решение с усечением для n=100:")
print(f"Ошибка: {np.linalg.norm(x_second_true_large - x_svd_large)}")

# Анализ сингулярных чисел
U_small, s_small, Vt_small = np.linalg.svd(A_small)
U_large, s_large, Vt_large = np.linalg.svd(A_large)

print(f"\nСингулярные числа для n=10: {s_small}")
print(f"Сингулярные числа для n=100 (первые 5): {s_large[:5]}")
print(f"Минимальное сингулярное число для n=100: {s_large[-1]}")

# Визуализация
# plt.figure(figsize=(15, 10))

# # Для n=10
# plt.subplot(2, 3, 1)
# plt.plot(x_second_true_small, 'bo-', label='Истинный x')
# plt.plot(x_second_recovered_small, 'ro-', label='Восстановленный x')
# plt.title('n=10: Обычное решение')
# plt.legend()

# plt.subplot(2, 3, 2)
# plt.plot(x_second_true_small, 'bo-', label='Истинный x')
# plt.plot(x_svd_small, 'go-', label='SVD решение')
# plt.title('n=10: SVD с усечением')
# plt.legend()

# plt.subplot(2, 3, 3)
# plt.semilogy(s_small, 'o-')
# plt.title('Сингулярные числа (n=10)')

# # Для n=100
# plt.subplot(2, 3, 4)
# plt.plot(x_second_true_large, 'b-', label='Истинный x')
# plt.plot(x_second_recovered_large, 'r-', label='Восстановленный x')
# plt.title('n=100: Обычное решение')
# plt.legend()

# plt.subplot(2, 3, 5)
# plt.plot(x_second_true_large, 'b-', label='Истинный x')
# plt.plot(x_svd_large, 'g-', label='SVD решение')
# plt.title('n=100: SVD с усечением')
# plt.legend()

# plt.subplot(2, 3, 6)
# plt.semilogy(s_large, 'o-')
# plt.title('Сингулярные числа (n=100)')

# plt.tight_layout()
# plt.show()

# print("\n" + "="*50)
# print("АНАЛИЗ ПРОБЛЕМЫ:")
# print("="*50)

print(f"Ранг матрицы A для n=10: {np.linalg.matrix_rank(A_small)}")
print(f"Ранг матрицы A для n=100: {np.linalg.matrix_rank(A_large)}")

# Проверим усл  овие совместимости
print(f"\nУсловие совместимости для n=100:")
print(f"b ∈ range(A): {np.allclose(b_second_large, A_large @ (A_large @ b_second_large))}")

# Альтернативное SVD решение с явным условием x_1 = 1
def solve_with_constraint(A, b, first_element=1):
    """Решаем с условием, что первый элемент x равен заданному значению"""
    n = A.shape[0]
    
    # Разделяем систему: A[:,1:]x[1:] = b - A[:,0]*first_element
    A_reduced = A[:, 1:]
    b_reduced = b - A[:, 0] * first_element
    
    # Решаем уменьшенную систему
    x_reduced = np.linalg.lstsq(A_reduced, b_reduced, rcond=None)[0]
    
    # Собираем полное решение
    x_full = np.zeros(n)
    x_full[0] = first_element
    x_full[1:] = x_reduced
    
    return x_full

x_constraint_small = solve_with_constraint(A_small, b_second_small)
x_constraint_large = solve_with_constraint(A_large, b_second_large)

print(f"\nРешение с ограничением x[0]=1 для n=10:")
print(f"Ошибка: {np.linalg.norm(x_second_true_small - x_constraint_small)}")

print(f"\nРешение с ограничением x[0]=1 для n=100:")
print(f"Ошибка: {np.linalg.norm(x_second_true_large - x_constraint_large)}")

Матрица A для n=10:
[[ 1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]

Определитель A для n=10: 1.0

Первый случай (единичный вектор):
Исходный x: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Восстановленный x: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Ошибка: 0.0

Второй случай для n=10:
Исходный x: [1.       2.       2.414214 2.732051 3.       3.236068 3.44949  3.645751
 3.828427 4.      ]
Восстановленный x: [1.       2.       2.414214 2.732051 3.       3.236068 3.44949  3.645751
 3.828427 4.      ]
Ошибка: 9.046021990402113e-14

Второй случай для n=100:
Ошибка: 143928433264120.9

SVD решение с усечением для n=10:
Ошибка: 2.89791716

/var/folders/j7/ms50hmkx4sxgmqrwysp2jpgm0000gn/T/ipykernel_61350/301335863.py:20: RuntimeWarning: divide by zero encountered in divide
  A_pinv = Vt.T @ np.diag(np.where(s_trunc != 0, 1/s_trunc, 0)) @ U.T


In [55]:
import numpy as np
from scipy.linalg import svd

n_small = 10
n_big = 100

def make_A(n):
    A = np.triu(np.full((n, n), -1.0))
    np.fill_diagonal(A, 1)
    return A

# Вектор решения: x_i = 1 + sqrt(i)
def make_x(n):
    return np.array([1 + np.sqrt(i) for i in range(n)])

# print("=== n = 10 ===")
A10 = make_A(n_small)
x_true10 = make_x(n_small)
b10 = A10 @ x_true10

# Обычное решение
x_direct10 = np.linalg.solve(A10, b10)
err10 = np.linalg.norm(x_direct10 - x_true10)
print(f"Обычное решение ошибка: {err10:.2e}")

# SVD решение
U10, s10, Vt10 = svd(A10)

s10_trunc = s10[:-1] 
U10_1 = U10[:, :-1]  # все кроме последнего столбца
V10_1 = Vt10[:-1, :].T  # все кроме последней строки

x_svd10 = V10_1 @ np.diag(1/s10_trunc) @ U10_1.T @ b10

# Корректируем константой чтобы x[0] = 1 + sqrt(0) = 1
V10_2 = Vt10[-1:, :].T  # последний правый вектор
# x[0] = x_svd[0] + c * v_n[0] = 1
c10 = (x_true10[0] - x_svd10[0]) / V10_2[0,0]
x_final10 = x_svd10 + c10 * V10_2.flatten()

err_svd10 = np.linalg.norm(x_final10 - x_true10)
print(f"SVD решение ошибка: {err_svd10:.2e}")

print("\nПроверка для n=10:")
print(f"x_true[0] = {x_true10[0]:.6f}")
#   , x_final[0] = {x_final10[0]:.6f}")
print("хорошо" if err_svd10 < 1e-10 else "Плохо")


A100 = make_A(n_big)
x_true100 = make_x(n_big)
b100 = A100 @ x_true100

x_direct100 = np.linalg.solve(A100, b100)
err100 = np.linalg.norm(x_direct100 - x_true100)
print(f"Обычное решение ошибка: {err100:.2e}")

U100, s100, Vt100 = svd(A100)

# Смотрим на сингулярные числа
# print(f"Сингулярные числа: {s100[0]:.2e} ... {s100[-1]:.2e}")
# print(f"Отношение min/max: {s100[-1]/s100[0]:.2e}")

s100_trunc = s100[:-1]
U100_1 = U100[:, :-1]
V100_1 = Vt100[:-1, :].T

x_svd100 = V100_1 @ np.diag(1/s100_trunc) @ U100_1.T @ b100

V100_2 = Vt100[-1:, :].T
if abs(V100_2[0,0]) > 1e-15:  
    c100 = (x_true100[0] - x_svd100[0]) / V100_2[0,0]
else:
    c100 = 0
    print("V100_2[0] близко к 0")

x_final100 = x_svd100 + c100 * V100_2.flatten()

err_svd100 = np.linalg.norm(x_final100 - x_true100)
print(f"SVD решение ошибка: {err_svd100:.2e}")

# print("\nПроверка для n=100:")
# print(f"x_true[0] = {x_true10[0]:.6f}")

# print("ИТОГ:")
# print(f"n=10:  обычное решение ошибка {err10:.2e}, SVD ошибка {err_svd10:.2e}")
# print(f"n=100: обычное решение ошибка {err100:.2e}, SVD ошибка {err_svd100:.2e}")

# if err_svd100 > 1e-5:
#     print("SVD работает плохо!")
# else:
    # print("? Что-то пошло не так...")

# Простая проверка Ax = b
# print(f"\nПроверка A@x = b для n=100:")
# b_check100 = A100 @ x_final100
# diff100 = np.linalg.norm(b_check100 - b100)
# print(f"Разница: {diff100:.2e}")

Обычное решение ошибка: 9.05e-14
SVD решение ошибка: 5.76e-15

Проверка для n=10:
x_true[0] = 1.000000
хорошо
Обычное решение ошибка: 1.44e+14
SVD решение ошибка: 2.25e-12


In [54]:
import numpy as np
from scipy.linalg import svd

def make_A(n):
    A = np.triu(np.full((n, n), -1.0))
    np.fill_diagonal(A, 1)
    return A

def make_x(n):
    return np.array([1 + np.sqrt(i) for i in range(n)])

sizes = [10, 50, 100]
results = []

print("СРАВНЕНИЕ МЕТОДОВ РЕШЕНИЯ")
print("=" * 50)
print(f"{'n':<8} {'Обычный метод':<15} {'SVD метод':<12}")
print("-" * 50)

for n in sizes:
    A = make_A(n)
    x_true = make_x(n)
    b = A @ x_true
    
    x_direct = np.linalg.solve(A, b)
    err_direct = np.linalg.norm(x_direct - x_true)
    
    # SVD решение
    U, s, Vt = svd(A)
    
    s_trunc = s[:-1] 
    U1 = U[:, :-1]
    V1 = Vt[:-1, :].T
    x_svd = V1 @ np.diag(1/s_trunc) @ U1.T @ b
    
    V2 = Vt[-1:, :].T
    if abs(V2[0,0]) > 1e-15:
        c = (x_true[0] - x_svd[0]) / V2[0,0]
    else:
        c = 0
    
    x_final = x_svd + c * V2.flatten()
    err_svd = np.linalg.norm(x_final - x_true)
    
 
    
    results.append((n, err_direct, err_svd, ))
    
    print(f"{n:<8} {err_direct:<15.2e} {err_svd:<12.2e}")

print("=" * 50)


for n, err_dir, err_svd in results:
    A = make_A(n)
    U, s, Vt = svd(A)
    cond_num = s[0] / s[-1] if s[-1] > 0 else float('inf')
    # print(f"n={n}: число обусловленности = {cond_num:.2e}")


СРАВНЕНИЕ МЕТОДОВ РЕШЕНИЯ
n        Обычный метод   SVD метод   
--------------------------------------------------
10       9.05e-14        5.76e-15    
50       5.93e-02        5.90e-13    
100      1.44e+14        2.25e-12    


In [1]:
import numpy as np
import math as m
from scipy.linalg import svd

randomGenerator = np.random.default_rng()

def generateTestMatrix(size):
    """
    Генерирует специальную тестовую матрицу
    - Главная диагональ: 1
    - Верхний треугольник: -1
    - Нижний треугольник: 0
    """
    matrix = np.full((size, size), -1.0)
    np.fill_diagonal(matrix, 1)
    matrix = np.triu(matrix)  # Обнуляем нижний треугольник
    return matrix

def createExactSolution(size, solutionType):
    """
    Создает точное решение системы
    solutionType = 1: вектор из единиц [1, 1, ..., 1]
    solutionType = 2: вектор [1 + sqrt(0), 1 + sqrt(1), ..., 1 + sqrt(n-1)]
    """
    if solutionType == 1:
        exactSolution = np.ones(size)
    elif solutionType == 2:
        exactSolution = np.ones(size)
        for i in range(size):
            exactSolution[i] += np.sqrt(i)
    return exactSolution

def computeRightHandSide(matrix, solution):
    """Вычисляет правую часть уравнения A*x = b"""
    return matrix @ solution

def solveLinearSystem(matrix, rightHandSide, exactSolution):
    """Решает систему линейных уравнений и вычисляет ошибку"""
    numericalSolution = np.linalg.solve(matrix, rightHandSide)
    solutionError = np.linalg.norm(numericalSolution - exactSolution)
    return numericalSolution, solutionError

def solveWithSVD(matrix, rightHandSide, exactSolution):
    """
    Решает вырожденную систему с помощью SVD
    Матрица имеет ранг n-1, поэтому одно сингулярное число равно 0
    """
    # Выполняем сингулярное разложение
    leftSingularVectors, singularValues, rightSingularVectorsTransposed = svd(matrix)
    
    # Убираем последнее (нулевое) сингулярное число
    truncatedSingularValues = singularValues[:-1]
    
    # Создаем обратную диагональную матрицу для ненулевых сингулярных чисел
    inverseSingularMatrix = np.diag(1.0 / truncatedSingularValues)
    
    # Разделяем U и V матрицы на соответствующие части
    leftSubmatrix = leftSingularVectors[:, :-1]
    rightSubmatrixTransposed = rightSingularVectorsTransposed[:-1, :]
    rightSubmatrix = rightSubmatrixTransposed.T
    
    # U2, V2 - соответствуют нулевому сингулярному числу
    rightNullspaceTransposed = rightSingularVectorsTransposed[-1:, :]
    rightNullspace = rightNullspaceTransposed.T
    
    # Вычисляем частное решение (лежащее в пространстве строк матрицы A)
    particularSolution = rightSubmatrix @ inverseSingularMatrix @ leftSubmatrix.T @ rightHandSide
    
    # Находим коэффициент для вектора из ядра (нуль-пространства)
    nullspaceCoefficient = (exactSolution[0] - particularSolution[0]) / rightNullspace[0]
    
    # Полное решение = частное решение + компонента из ядра
    fullSolution = particularSolution + nullspaceCoefficient * rightNullspace.flatten()
    
    return fullSolution

# Основная часть программы
if __name__ == "__main__":
    print("=== АНАЛИЗ ВЫРОЖДЕННЫХ СИСТEM ЛИНЕЙНЫХ УРАВНЕНИЙ ===\n")
    
    # Тест 1: Прямое решение для маленькой матрицы
    matrixSize1 = 5
    testMatrix1 = generateTestMatrix(matrixSize1)
    exactSolution1 = createExactSolution(matrixSize1, 2)
    rightHandSide1 = computeRightHandSide(testMatrix1, exactSolution1)
    
    numericalSolution1, error1 = solveLinearSystem(testMatrix1, rightHandSide1, exactSolution1)
    
    print("ТЕСТ 1: Прямое решение (n=5)")
    print(f"Ошибка: {error1:.3e}")
    print(f"Точное решение: {exactSolution1}")
    print(f"Численное решение: {numericalSolution1}")
    print(f"Матрица системы:\n{testMatrix1}")
    
    print("\n" + "="*50 + "\n")
    
    # Тест 2: Решение через SVD для большой вырожденной матрицы
    matrixSize2 = 50
    testMatrix2 = generateTestMatrix(matrixSize2)
    exactSolution2 = createExactSolution(matrixSize2, 2)
    rightHandSide2 = computeRightHandSide(testMatrix2, exactSolution2)
    
    svdSolution = solveWithSVD(testMatrix2, rightHandSide2, exactSolution2)
    error2 = np.linalg.norm(svdSolution - exactSolution2)
    
    print("ТЕСТ 2: SVD решение для вырожденной системы (n=50)")
    print(f"Ошибка: {error2:.5e}")
    print(f"Первые 5 элементов точного решения: {exactSolution2[:5]}")
    print(f"Первые 5 элементов SVD решения: {svdSolution[:5]}")
    
    # Дополнительный анализ: проверка ранга матрицы
    print("\n" + "="*50)
    print("АНАЛИЗ МАТРИЦЫ:")
    print(f"Размер матрицы: {testMatrix2.shape}")
    print(f"Ранг матрицы: {np.linalg.matrix_rank(testMatrix2)}")
    print(f"Определитель матрицы: {np.linalg.det(testMatrix2):.2e}")
    
    # Проверка сингулярных чисел
    singularValues = svd(testMatrix2, compute_uv=False)
    print(f"Сингулярные числа (первые 5): {singularValues[:5]}")
    print(f"Минимальное сингулярное число: {singularValues.min():.2e}")

=== АНАЛИЗ ВЫРОЖДЕННЫХ СИСТEM ЛИНЕЙНЫХ УРАВНЕНИЙ ===

ТЕСТ 1: Прямое решение (n=5)
Ошибка: 1.831e-15
Точное решение: [1.         2.         2.41421356 2.73205081 3.        ]
Численное решение: [1.         2.         2.41421356 2.73205081 3.        ]
Матрица системы:
[[ 1. -1. -1. -1. -1.]
 [ 0.  1. -1. -1. -1.]
 [ 0.  0.  1. -1. -1.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  1.]]


ТЕСТ 2: SVD решение для вырожденной системы (n=50)
Ошибка: 5.89519e-13
Первые 5 элементов точного решения: [1.         2.         2.41421356 2.73205081 3.        ]
Первые 5 элементов SVD решения: [1.         2.         2.41421356 2.73205081 3.        ]

АНАЛИЗ МАТРИЦЫ:
Размер матрицы: (50, 50)
Ранг матрицы: 49
Определитель матрицы: 1.00e+00
Сингулярные числа (первые 5): [30.91044381 10.39469994  6.34480805  4.64521302  3.72699246]
Минимальное сингулярное число: 2.67e-15


# Подробное решение задач по финансовой математике

## Задача 1: Par Strike для Quanto-Compo Forward

### Постановка задачи

Рассмотрим кросс-валютный рынок Блэка-Шоулза с четырьмя базовыми активами:

1. **Банковский счет в domestic валюте**: $dB_t^d = r^d B_t^d dt$
2. **Банковский счет в foreign валюте**: $dB_t^f = r^f B_t^f dt$  
3. **Иностранная акция** $S_t$ (цена в foreign валюте)
4. **Обменный курс** $X_t$ (количество domestic валюты за 1 единицу foreign валюты)

**Динамика под реальной мерой $\mathbb{P}$**:
```math
\begin{aligned}
\frac{dS_t}{S_t} &= \mu_S dt + \sigma_S dW_t^S \\
\frac{dX_t}{X_t} &= \mu_X dt + \sigma_X dW_t^X \\
d\langle W^S, W^X\rangle_t &= \rho dt
\end{aligned}
```

**Контракт**: выплачивает в момент $T$ сумму $S_T X_{T-\tau} - K$, где $0 < \tau < T$

**Цель**: найти паритетный страйк $K$ при $t=0$

---

### Подробное решение

#### Шаг 1: Условие отсутствия арбитража

Стоимость контракта в начальный момент времени должна быть равна нулю:

```math
V_0 = \mathbb{E}^{Q^d} \left[ e^{-r^d T} (S_T X_{T-\tau} - K) \right] = 0
```

где $Q^d$ - domestic risk-neutral мера.

**Обоснование**: В отсутствие арбитража сегодняшняя стоимость любого контракта равна математическому ожиданию дисконтированных будущих выплат под риск-нейтральной мерой.

Преобразуем:
```math
e^{-r^d T} \mathbb{E}^{Q^d}[S_T X_{T-\tau}] - e^{-r^d T} K = 0
```

Умножаем на $e^{r^d T}$:
```math
K = \mathbb{E}^{Q^d}[S_T X_{T-\tau}]
```

#### Шаг 2: Нахождение динамики под risk-neutral мерой

**Для обменного курса $X_t$**:

Рассмотрим актив $X_t B_t^f$ - иностранный банковский счет, выраженный в domestic валюте. Этот актив должен быть мартингалом при дисконтировании на $B_t^d$:

```math
\frac{X_t B_t^f}{B_t^d} \text{ - мартингал под } Q^d
```

**Обоснование**: По первой фундаментальной теореме asset pricing, все торгуемые активы, дисконтированные на нумераire, должны быть мартингалами под risk-neutral мерой.

Отсюда получаем динамику:
```math
\frac{dX_t}{X_t} = (r^d - r^f)dt + \sigma_X dW_t^{X,Q^d}
```

**Для акции $S_t$**:

Акция $S_t$ сама по себе не является торгуемым активом для domestic инвестора. Торгуемым активом является $S_t X_t$ - цена акции в domestic валюте.

**Обоснование**: Domestic инвестор может купить акцию только через обмен валюты, поэтому его реальный доход определяется произведением $S_t X_t$.

Процесс $\frac{S_t X_t}{B_t^d}$ должен быть мартингалом под $Q^d$. Применяя формулу Ито для произведения:
```math
d(S_t X_t) = S_t dX_t + X_t dS_t + dS_t dX_t
```

Подставляя динамики и приравнивая дрифт к $r^d$, получаем:
```math
\frac{dS_t}{S_t} = (r^f - \rho\sigma_S \sigma_X)dt + \sigma_S dW_t^{S,Q^d}
```

**Член $-\rho\sigma_S \sigma_X$** - это "поправка на квантирование", возникающая из-за корреляции между акцией и валютным курсом.

#### Шаг 3: Решение стохастических дифференциальных уравнений

Интегрируем SDE под мерой $Q^d$:

**Для акции**:
```math
S_T = S_0 \exp\left[ \left(r^f - \rho\sigma_S \sigma_X - \frac{\sigma_S^2}{2}\right)T + \sigma_S W_T^{S,Q^d} \right]
```

**Для обменного курса**:
```math
X_{T-\tau} = X_0 \exp\left[ \left(r^d - r^f - \frac{\sigma_X^2}{2}\right)(T-\tau) + \sigma_X W_{T-\tau}^{X,Q^d} \right]
```

**Обоснование**: Используем лемму Ито для логнормальных процессов. Если $d\ln Y_t = \mu dt + \sigma dW_t$, то $Y_t = Y_0 \exp[(\mu - \frac{\sigma^2}{2})t + \sigma W_t]$.

#### Шаг 4: Вычисление математического ожидания

Мы хотим вычислить:
```math
K = \mathbb{E}^{Q^d}[S_T X_{T-\tau}] = S_0 X_0 \exp(A) \cdot \mathbb{E}^{Q^d}[\exp(U)]
```
где:
```math
\begin{aligned}
A &= \left(r^f - \rho\sigma_S \sigma_X - \frac{\sigma_S^2}{2}\right)T + \left(r^d - r^f - \frac{\sigma_X^2}{2}\right)(T-\tau) \\
U &= \sigma_S W_T^{S,Q^d} + \sigma_X W_{T-\tau}^{X,Q^d}
\end{aligned}
```

**Ключевое наблюдение**: $U$ - гауссовская случайная величина с нулевым средним.

Для гауссовской величины $Z \sim N(0,\sigma^2)$:
```math
\mathbb{E}[e^Z] = \exp\left(\frac{\sigma^2}{2}\right)
```

**Вычисляем дисперсию** $U$:
```math
\begin{aligned}
\text{Var}(U) &= \sigma_S^2 \text{Var}(W_T^{S,Q^d}) + \sigma_X^2 \text{Var}(W_{T-\tau}^{X,Q^d}) + 2\sigma_S\sigma_X \text{Cov}(W_T^{S,Q^d}, W_{T-\tau}^{X,Q^d}) \\
&= \sigma_S^2 T + \sigma_X^2 (T-\tau) + 2\rho\sigma_S\sigma_X (T-\tau)
\end{aligned}
```

**Обоснование**: $\text{Cov}(W_T^S, W_{T-\tau}^X) = \rho \cdot \min(T, T-\tau) = \rho(T-\tau)$, так как $\tau > 0$.

Таким образом:
```math
\mathbb{E}^{Q^d}[\exp(U)] = \exp\left( \frac{1}{2}[\sigma_S^2 T + \sigma_X^2 (T-\tau) + 2\rho\sigma_S\sigma_X (T-\tau)] \right)
```

#### Шаг 5: Упрощение выражения

Подставляем все обратно:
```math
K = S_0 X_0 \exp\left( A + \frac{1}{2}[\sigma_S^2 T + \sigma_X^2 (T-\tau) + 2\rho\sigma_S\sigma_X (T-\tau)] \right)
```

Раскрываем $A$:
```math
\begin{aligned}
A &= r^f T - \rho\sigma_S\sigma_X T - \frac{\sigma_S^2}{2}T + r^d(T-\tau) - r^f(T-\tau) - \frac{\sigma_X^2}{2}(T-\tau) \\
&= r^f\tau + r^d(T-\tau) - \rho\sigma_S\sigma_X T - \frac{\sigma_S^2}{2}T - \frac{\sigma_X^2}{2}(T-\tau)
\end{aligned}
```

Складываем с половинкой дисперсии:
```math
\begin{aligned}
&A + \frac{1}{2}[\sigma_S^2 T + \sigma_X^2 (T-\tau) + 2\rho\sigma_S\sigma_X (T-\tau)] \\
&= r^f\tau + r^d(T-\tau) - \rho\sigma_S\sigma_X T - \frac{\sigma_S^2}{2}T - \frac{\sigma_X^2}{2}(T-\tau) \\
&\quad + \frac{\sigma_S^2}{2}T + \frac{\sigma_X^2}{2}(T-\tau) + \rho\sigma_S\sigma_X (T-\tau) \\
&= r^f\tau + r^d(T-\tau) - \rho\sigma_S\sigma_X\tau
\end{aligned}
```

---

### Итоговый ответ для Задачи 1

```math
\boxed{K = S_0 X_0 \exp\left( r^f \tau + r^d (T-\tau) - \rho\sigma_S \sigma_X \tau \right)}
```

**Экономическая интерпретация**:
- $r^f\tau$ - доходность на foreign рынке за период $\tau$
- $r^d(T-\tau)$ - доходность на domestic рынке за оставшийся период
- $-\rho\sigma_S\sigma_X\tau$ - поправка на корреляцию между акцией и валютой

---

## Задача 2: Вес $\alpha_t$ в LGM модели

### Постановка задачи

**LGM модель**:
```math
dx_t = \sigma(t) dW_t, \quad x_0 = 0
```
Динамика задана относительно мартингальной меры $\mathbb{Q}^N$.

**Нумераire**:
```math
N_t = \frac{1}{P(0,t)} \exp\left( h(t) x_t + a(t) \right), \quad a(0) = 0
```

**Найти**: вес $\alpha_t$ такой, что:
```math
\frac{dN_t}{N_t} = \alpha_t \frac{dB_t}{B_t} + (1 - \alpha_t) \frac{dP(t,T)}{P(t,T)}
```

---

### Подробное решение

#### Шаг 1: Динамика нумераire $N_t$

Прологарифмируем:
```math
\ln N_t = -\ln P(0,t) + h(t) x_t + a(t)
```

Дифференцируем используя лемму Ито:
```math
d(\ln N_t) = -d(\ln P(0,t)) + h'(t) x_t dt + h(t) dx_t + a'(t) dt
```

**Замечание**: $P(0,t)$ - детерминированная функция времени, поэтому:
```math
d(\ln P(0,t)) = \frac{\partial}{\partial t} \ln P(0,t) dt
```

Из определения кратковременной процентной ставки:
```math
r_t = -\frac{\partial}{\partial t} \ln P(0,t)
```

Таким образом:
```math
d(\ln N_t) = r_t dt + h'(t) x_t dt + h(t) dx_t + a'(t) dt
```

Подставляем $dx_t = \sigma(t) dW_t^N$:
```math
d(\ln N_t) = [r_t + h'(t) x_t + a'(t)] dt + h(t) \sigma(t) dW_t^N
```

**Переход к $dN_t/N_t$**:

По лемме Ито: если $d\ln Y_t = \mu_t dt + \nu_t dW_t$, то:
```math
\frac{dY_t}{Y_t} = (\mu_t + \frac{1}{2}\nu_t^2) dt + \nu_t dW_t
```

Применяем к $N_t$:
```math
\frac{dN_t}{N_t} = \left[ r_t + h'(t) x_t + a'(t) + \frac{1}{2}h(t)^2 \sigma(t)^2 \right] dt + h(t) \sigma(t) dW_t^N
```

**Волатильность $N_t$**: $h(t)\sigma(t)$

#### Шаг 2: Динамика облигации $P(t,T)$

В LGM модели:
```math
P(t,T) = \frac{P(0,T)}{P(0,t)} \exp\left( - (h(T) - h(t)) x_t - \frac{1}{2}(h(T)^2 - h(t)^2) \zeta(t) \right)
```
где $\zeta(t) = \int_0^t \sigma(s)^2 ds$.

Прологарифмируем:
```math
\ln P(t,T) = \ln P(0,T) - \ln P(0,t) - (h(T) - h(t)) x_t - \frac{1}{2}(h(T)^2 - h(t)^2) \zeta(t)
```

Дифференцируем:
```math
\begin{aligned}
d(\ln P(t,T)) = &-d(\ln P(0,t)) - (h(T) - h(t)) dx_t - x_t d(h(T) - h(t)) \\
& - \frac{1}{2}(h(T)^2 - h(t)^2) d\zeta(t) - \zeta(t) d\left( \frac{1}{2}(h(T)^2 - h(t)^2) \right)
\end{aligned}
```

Упрощаем:
- $d(\ln P(0,t)) = -r_t dt$
- $d(h(T) - h(t)) = -h'(t) dt$ (так как $h(T)$ не зависит от $t$)
- $d\zeta(t) = \sigma(t)^2 dt$
- $d(h(T)^2 - h(t)^2) = -2h(t)h'(t) dt$

Получаем:
```math
\begin{aligned}
d(\ln P(t,T)) = &\left[ r_t + h'(t) x_t - \frac{1}{2}(h(T)^2 - h(t)^2) \sigma(t)^2 + h(t)h'(t) \zeta(t) \right] dt \\
& - (h(T) - h(t)) \sigma(t) dW_t^N
\end{aligned}
```

**Переход к $dP(t,T)/P(t,T)$**:

Снова применяем лемму Ито:
```math
\frac{dP(t,T)}{P(t,T)} = \left[ \mu_t + \frac{1}{2}\nu_t^2 \right] dt + \nu_t dW_t^N
```
где:
```math
\begin{aligned}
\mu_t &= r_t + h'(t) x_t - \frac{1}{2}(h(T)^2 - h(t)^2) \sigma(t)^2 + h(t)h'(t) \zeta(t) \\
\nu_t &= - (h(T) - h(t)) \sigma(t)
\end{aligned}
```

**Волатильность $P(t,T)$**: $-(h(T) - h(t)) \sigma(t)$

#### Шаг 3: Приравнивание волатильностей

Из условия:
```math
\frac{dN_t}{N_t} = \alpha_t \frac{dB_t}{B_t} + (1 - \alpha_t) \frac{dP(t,T)}{P(t,T)}
```

Заметим:
- $\frac{dB_t}{B_t} = r_t dt$ (нулевая волатильность)
- Волатильность левой части: $h(t)\sigma(t)$
- Волатильность правой части: $(1 - \alpha_t) \cdot [-(h(T) - h(t)) \sigma(t)]$

Приравниваем волатильности:
```math
h(t)\sigma(t) = -(1 - \alpha_t)(h(T) - h(t)) \sigma(t)
```

Сокращаем $\sigma(t)$ (предполагая $\sigma(t) \neq 0$):
```math
h(t) = -(1 - \alpha_t)(h(T) - h(t))
```

#### Шаг 4: Решение для $\alpha_t$

Решаем уравнение:
```math
\begin{aligned}
h(t) &= -(1 - \alpha_t)h(T) + (1 - \alpha_t)h(t) \\
h(t) - (1 - \alpha_t)h(t) &= -(1 - \alpha_t)h(T) \\
\alpha_t h(t) &= -(1 - \alpha_t)h(T) \\
\alpha_t h(t) &= -h(T) + \alpha_t h(T) \\
\alpha_t (h(t) - h(T)) &= -h(T)
\end{aligned}
```

---

### Итоговый ответ для Задачи 2

```math
\boxed{\alpha_t = \frac{h(T)}{h(T) - h(t)}}
```

**Интерпретация**: Вес $\alpha_t$ показывает, какая доля капитала должна быть инвестирована в банковский счет, чтобы реплицировать нумераire $N_t$ с помощью банковского счета и облигации.

---

## Заключение

Обе задачи демонстрируют важные техники финансовой математики:

1. **Задача 1**: Использование смены меры, вычисление ожиданий от произведений логнормальных величин, учет корреляции между активами
2. **Задача 2**: Работа с LGM моделью, вычисление динамик процессов, техника репликации с помощью базовых активов

Полученные формулы имеют четкую экономическую интерпретацию и могут быть использованы на практике для pricing и hedging соответствующих финансовых инструментов.

Прекрасный вопрос! Давайте пройдем через этот вывод максимально подробно, шаг за шагом.

## Вывод динамики обменного курса под risk-neutral мерой

### Исходные данные

У нас есть:
1. **Динамика обменного курса под реальной мерой** \(\mathbb{P}\):
   ```math
   \frac{dX_t}{X_t} = \mu_X dt + \sigma_X dW_t^{X,\mathbb{P}}
   ```

2. **Банковские счета**:
   ```math
   \begin{aligned}
   dB_t^d &= r^d B_t^d dt \\
   dB_t^f &= r^f B_t^f dt
   \end{aligned}
   ```

3. **Мартингальное условие**:
   ```math
   \frac{X_t B_t^f}{B_t^d} \text{ является мартингалом под } Q^d
   ```

---

### Шаг 1: Запишем процесс, который должен быть мартингалом

Рассмотрим процесс:
```math
Y_t = \frac{X_t B_t^f}{B_t^d}
```

Нам нужно найти динамику \(Y_t\) и потребовать, чтобы её дрифт был равен нулю.

---

### Шаг 2: Найдем динамику каждого компонента

**Для \(X_t\)** (пока под реальной мерой):
```math
dX_t = \mu_X X_t dt + \sigma_X X_t dW_t^{X,\mathbb{P}}
```

**Для \(B_t^f\)**:
```math
dB_t^f = r^f B_t^f dt
```

**Для \(B_t^d\)**:
```math
dB_t^d = r^d B_t^d dt
```

**Для \(1/B_t^d\)** (используем лемму Ито):
```math
\begin{aligned}
d\left(\frac{1}{B_t^d}\right) &= -\frac{1}{(B_t^d)^2} dB_t^d + \frac{1}{2} \cdot 2 \cdot \frac{1}{(B_t^d)^3} (dB_t^d)^2 \\
&= -\frac{1}{(B_t^d)^2} r^d B_t^d dt + \frac{1}{(B_t^d)^3} \cdot 0 \\
&= -r^d \frac{1}{B_t^d} dt
\end{aligned}
```

---

### Шаг 3: Применяем формулу Ито для произведения трёх процессов

Мы хотим найти \(dY_t = d(X_t B_t^f \cdot \frac{1}{B_t^d})\)

Сначала найдем \(dZ_t = d(X_t B_t^f)\):

```math
\begin{aligned}
dZ_t &= d(X_t B_t^f) \\
&= B_t^f dX_t + X_t dB_t^f + dX_t dB_t^f \\
&= B_t^f (\mu_X X_t dt + \sigma_X X_t dW_t^{X,\mathbb{P}}) + X_t (r^f B_t^f dt) + 0 \\
&= X_t B_t^f [(\mu_X + r^f) dt + \sigma_X dW_t^{X,\mathbb{P}}]
\end{aligned}
```

Теперь найдем \(dY_t = d(Z_t \cdot \frac{1}{B_t^d})\):

```math
\begin{aligned}
dY_t &= d\left(Z_t \cdot \frac{1}{B_t^d}\right) \\
&= \frac{1}{B_t^d} dZ_t + Z_t d\left(\frac{1}{B_t^d}\right) + dZ_t d\left(\frac{1}{B_t^d}\right)
\end{aligned}
```

Подставляем выражения:

```math
\begin{aligned}
dY_t &= \frac{1}{B_t^d} \left[ X_t B_t^f (\mu_X + r^f) dt + X_t B_t^f \sigma_X dW_t^{X,\mathbb{P}} \right] \\
&\quad + X_t B_t^f \left( -r^d \frac{1}{B_t^d} dt \right) \\
&\quad + \left[ X_t B_t^f (\mu_X + r^f) dt + X_t B_t^f \sigma_X dW_t^{X,\mathbb{P}} \right] \cdot \left( -r^d \frac{1}{B_t^d} dt \right)
\end{aligned}
```

Упрощаем, замечая что \(Y_t = \frac{X_t B_t^f}{B_t^d}\):

```math
\begin{aligned}
dY_t &= Y_t (\mu_X + r^f) dt + Y_t \sigma_X dW_t^{X,\mathbb{P}} - Y_t r^d dt + 0 \\
&= Y_t [(\mu_X + r^f - r^d) dt + \sigma_X dW_t^{X,\mathbb{P}}]
\end{aligned}
```

---

### Шаг 4: Переход к risk-neutral мере и условие мартингальности

Под мерой \(Q^d\) процесс \(Y_t\) должен быть мартингалом, значит его дрифт должен быть равен нулю:

```math
\mu_X + r^f - r^d = 0
```

Отсюда:
```math
\mu_X = r^d - r^f
```

Подставляем обратно в динамику \(X_t\), но теперь под мерой \(Q^d\):

```math
\frac{dX_t}{X_t} = (r^d - r^f) dt + \sigma_X dW_t^{X,Q^d}
```

---

### Шаг 5: Почему волатильность не меняется?

При переходе от меры \(\mathbb{P}\) к мере \(Q^d\) через теорему Гирсанова:
- **Дрифт меняется** (мы только что это нашли)
- **Волатильность сохраняется**

Математически: если 
```math
dW_t^{\mathbb{P}} = dW_t^{Q^d} + \lambda_t dt
```
то стохастическая часть \(dW_t\) не меняет свою "силу" (квадратическую вариацию).

---

### Финансовая интуиция

Полученная динамика имеет простой финансовый смысл:

- Если \(r^d > r^f\), то domestic валюта должна **дешеветь** относительно foreign валюты (\(X_t\) растет)
- Если \(r^f > r^d\), то domestic валюта должна **дорожать** относительно foreign валюты (\(X_t\) падает)
- Это отражает **паритет процентных ставок**: разница в процентных ставках компенсируется изменением обменного курса

**Пример**:
- \(r^d = 10\%\), \(r^f = 1\%\)
- Тогда \(\mu_X = 10\% - 1\% = 9\%\)
- RUB должен дешеветь относительно USD на 9% в год в среднем

---

### Итоговый результат

```math
\boxed{\frac{dX_t}{X_t} = (r^d - r^f)dt + \sigma_X dW_t^{X,Q^d}}
```

Это фундаментальный результат, который:
1. Исключает арбитраж между валютами
2. Согласуется с теорией паритета процентных ставок
3. Позволяет корректно оценивать производные инструменты в кросс-валютных моделях